### PR TITLE
Added option to run programs with arguments

### PR DESCRIPTION
**Pull request by rsvalerio**
Example: "firefox -P development" to open firefox in development profile

### CODE REVIEW

**Comment by yocontra** [comment]
+1000 - needs docs though

**Comment by moshmage** [comment]
Welp. Since this merge was never accepted I had to copy-paste this onto the project..

**Comment by sindresorhus** [comment]
[`opn`](https://github.com/sindresorhus/opn) supports this.

**Comment by rsvalerio** [comment]
As aways, great work @sindresorhus , thank you.

**Pull request closed without merging**
